version: '2'

services:
  web:
    build: .
    command: python3 dog_shelter.py
    ports:
     - "5000:5000"
    volumes:
     - .:/code


  web2:
    build: ./Web_server-master
    command: python ./Web_server-master/app.py
    ports:
      - "81:5000"
    depends_on:
      - web
    volumes:
     - .:/code



