version: '2'

services:
  
  web2:
    build: ./Web_server-master
    command: python ./Web_server-master/app.py runserver 0.0.0.0:81
    ports:
      - "81:5000"
    volumes:
      - .:/code
    
  web:
    build: .
    command: python3 dog_shelter.py 
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    links:
      - web2



